#数据源配置
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  #禁用thymeleaf缓存
  thymeleaf:
    cache: false
#加载mybatis配置文件
mybatis:
  #指定mapper映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #设置类型别名
  type-aliases-package: com.etc.travelsys.model

#mybatis sql打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.etc.travelsys.mapper: debug